# Generated by Django 2.0.1 on 2018-01-29 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstanding',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
