# Generated by Django 2.0.1 on 2018-01-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_academicstanding_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstanding',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_standings', to='students.Student'),
        ),
    ]
