# Generated by Django 2.0.1 on 2018-01-29 15:04

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180129_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=students.models.generate_name, max_length=20),
        ),
    ]
